In [41]:
# IMPORTS

import pandas as pd
import os

In [42]:
# PATHS

path_raw = os.path.join('..', 'data', 'raw')

file_clock = os.path.join(path_raw, 'raw_africa_clock_15_35.xlsx')
file_edu_unemp = os.path.join(path_raw, 'Data_africa_education_unemployed.csv')
file_sector = os.path.join(path_raw, 'Data_africa_sector_employed.csv')

In [43]:
# LOAD DATASETS

df_clock = pd.read_excel(file_clock)

df_edu_unemp = pd.read_csv(file_edu_unemp)

df_sector = pd.read_csv(file_sector)

In [44]:
# DATASET DICTIONARY

datasets = {
    "clock": df_clock,
    "education_unemployment": df_edu_unemp,
    "sector_employment": df_sector
}

In [45]:
# OVERVIEW OF DATASETS

for name, df in datasets.items():

    print(f"{'='*60}")
    print(f"DATASET : {name.upper()}")
    print(f"{'='*60}")

    print("Columns:")
    print(df.columns.tolist())

    print("First 3 rows:")
    display(df.head(3))

============================================================
DATASET : CLOCK
============================================================
Columns:
['ccode', 'country', 'year', 'age', 'gender', 'sector', 'sector_group', 'population']
First 3 rows:

,ccode,country,year,age,gender,sector,sector_group,population
0,AGO,Angola,2026,15,female,Agriculture; forestry and fishing,Agriculture,113448
1,AGO,Angola,2026,15,female,"Arts, entertainment and recreation",Services,116
2,AGO,Angola,2026,15,female,Construction,Industry,111

============================================================
DATASET : EDUCATION_UNEMPLOYMENT
============================================================
Columns:
['ccode', 'year', 'edu_ilo', 'age_group', 'gender', 'share_unemp', 'share_inact']
First 3 rows:

  ccode  year            edu_ilo age_group  gender  share_unemp  share_inact
0   AGO  2015  Less than primary     15-24  female     0.056506     0.613708
1   AGO  2016  Less than primary     15-24  female     0.054342     0.532776
2   AGO  2017  Less than primary     15-24  female     0.052178     0.451844

============================================================
DATASET : SECTOR_EMPLOYMENT
============================================================
Columns:
['ccode', 'year', 'gender', 'age', 'broad_sector', 'sector21', 'population']
First 3 rows:

,ccode,year,gender,age,broad_sector,sector21,population
0,AGO,2015,Female,15,Services,Accommodation and food service activities,1300.0
1,AGO,2015,Female,16,Services,Accommodation and food service activities,1242.0
2,AGO,2015,Female,17,Services,Accommodation and food service activities,1192.0

In [46]:
# DATASET INFO

for name, df in datasets.items():

    print(f"{'='*60}")
    print(f"INFO : {name.upper()}")
    print(f"{'='*60}")

    df.info()

============================================================
INFO : CLOCK
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 46746 entries, 0 to 46745
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ccode         46746 non-null  str
 1   country       46746 non-null  str
 2   year          46746 non-null  int64
 3   age           46746 non-null  int64
 4   gender        46746 non-null  str
 5   sector        46746 non-null  str
 6   sector_group  46746 non-null  str
 7   population    46746 non-null  int64
dtypes: int64(3), str(5)
memory usage: 2.9 MB
============================================================
INFO : EDUCATION_UNEMPLOYMENT
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 17820 entries, 0 to 17819
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ccode        17820 non-null  str
 1   year         17820 non-null  int64
 2   edu_ilo      17820 non-null  str
 3   age_group    17820 non-null  str
 4   gender       17820 non-null  str
 5   share_unemp  17820 non-null  float64
 6   share_inact  17820 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 974.7 KB
============================================================
INFO : SECTOR_EMPLOYMENT
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 1224300 entries, 0 to 1224299
Data columns (total 7 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   ccode         1224300 non-null  str
 1   year          1224300 non-null  int64
 2   gender        1224300 non-null  str
 3   age           1224300 non-null  int64
 4   broad_sector  1224300 non-null  str
 5   sector21      1224300 non-null  str
 6   population    1224300 non-null  float64
dtypes: float64(1), int64(2), str(4)
memory usage: 65.4 MB

In [47]:
# 7. DESCRIPTIVE STATISTICS

for name, df in datasets.items():

    print(f"{'='*60}")
    print(f"STATISTICS : {name.upper()}")
    print(f"{'='*60}")

    display(df.describe())

============================================================
STATISTICS : CLOCK
============================================================

          year           age     population
count  46746.0  46746.000000   46746.000000
mean    2026.0     25.000000    6663.657575
std        0.0      6.055365   32659.058076
min     2026.0     15.000000       0.000000
25%     2026.0     20.000000      86.000000
50%     2026.0     25.000000     410.500000
75%     2026.0     30.000000    2297.000000
max     2026.0     35.000000  951413.000000

============================================================
STATISTICS : EDUCATION_UNEMPLOYMENT
============================================================

               year   share_unemp   share_inact
count  17820.000000  17820.000000  17820.000000
mean    2020.000000      0.124678      0.398638
std        3.162366      0.146570      0.238671
min     2015.000000      0.000000      0.000000
25%     2017.000000      0.036170      0.195110
50%     2020.000000      0.066350      0.361782
75%     2023.000000      0.152940      0.586081
max     2025.000000      0.950000      0.950000

============================================================
STATISTICS : SECTOR_EMPLOYMENT
============================================================

               year           age    population
count  1.224300e+06  1.224300e+06  1.224300e+06
mean   2.020000e+03  3.950000e+01  4.187975e+03
std    3.162279e+00  1.443088e+01  2.164336e+04
min    2.015000e+03  1.500000e+01  0.000000e+00
25%    2.017000e+03  2.700000e+01  4.900000e+01
50%    2.020000e+03  3.950000e+01  2.590000e+02
75%    2.023000e+03  5.200000e+01  1.371000e+03
max    2.025000e+03  6.400000e+01  9.089370e+05

In [48]:
# MISSING VALUES

for name, df in datasets.items():

    print(f"{name.upper()} - Missing values")

    print(df.isnull().sum())

CLOCK - Missing values
ccode           0
country         0
year            0
age             0
gender          0
sector          0
sector_group    0
population      0
dtype: int64
EDUCATION_UNEMPLOYMENT - Missing values
ccode          0
year           0
edu_ilo        0
age_group      0
gender         0
share_unemp    0
share_inact    0
dtype: int64
SECTOR_EMPLOYMENT - Missing values
ccode           0
year            0
gender          0
age             0
broad_sector    0
sector21        0
population      0
dtype: int64

In [49]:
# DUPLICATES

for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(f"\n{name.upper()} - Duplicates: {duplicates}")

CLOCK - Duplicates: 0

EDUCATION_UNEMPLOYMENT - Duplicates: 0

SECTOR_EMPLOYMENT - Duplicates: 0